#spring:
#  redis:
#    host: ${REDIS_HOST:localhost}
#    port: ${REDIS_PORT:6379}
#    ##password: ${REDIS_PASSWORD:}
#  #spring boot admin的登陆账号和密码配置
#  security:
#    user:
#      name: admin
#      password: 123456


#日志相关配置
#logging:
#  level:
#    org.springframework.security: DEBUG
#  path: logs/
#  file:
#    max-size: 1GB


